% @author: Khyati K.Vyas
function [decision] = capChecker(fn)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CHECKER FUNCTION TO DETECT IF CAP IS %
% PRESENT OR NOT                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


close all;
addpath('../TEST_IMAGES');

%READ THE IMAGE
im=imread(fn);


%CROPPING THE PART OF THE BOTTLE WHICH CONTAINS ONLY THE CENTER BOTTLE.I CALCULATED
%THE APPROXIMATE LOCATION OF THE BOTTLE AND GAVE THE FOLLOWING COORDIANTES AND
%WIDTH AND HEIGHT.
im_Bottle = imcrop(im,[103 0.5 130 800]);
%imshow(im_Bottle);

%CROPPING THE PART OF THE BOTTLE WHICH CONTAINS ONLY THE CAP.I CALCULATED
%THE APPROXIMATE LOCATION OF THE CAP AND GAVE THE FOLLOWING COORDIANTES AND
%WIDTH AND HEIGHT.

im_Cap=imcrop(im_Bottle,[54   12  38  25]);
%imshow(im_Cap);

%THIS CALCULATES THE VALUE OF R,G,B FOR EACH PIXEL IN THE IMAGE. 38 AND 25
%ARE THE HEIGHT AND WIDTH OF THE IMAGE CALCULATED IN THE PREVIOUS STEP.
p=impixel(im_Cap,38,25);
%disp(p);


%SINCE THE CAP IS RED IN COLOR,I USE THE GREEN AND BLUE PIXEL VALUES. THUS
%USING THE DATA CURSOR, I CHECKED THE VALUES FOR GREEN AND BLUE OF PIXELS
%WHEN THE CAP IS PRESENT AND WHEN IT IS NOT. THIS GAVE ME A THRESHOLD THAT
%WILL DECIDE WHETHER THE BOTTLE CAP IS PRESENT OR NOT. IF IT IS PRESENT IT
%WILL GO ON TO CHECK IF THE LABEL IS PRESENT.
if(p(2)>=100 && p(3)>=100)
    %disp('Cap not present. Botttle is defective');
    decision=false;
    return;
    
else
    decision=true;
    return;
end